// example/react/src/App.js
import React from "react";

import image from "./assets/Macaca_nigra_self-portrait_large.jpg";
import imagePlaceholder from "./assets/Macaca_nigra_self-portrait_large.jpg?placeholder";

function App() {
  return (
    <div className="App">
      <img
        style={{ width: 728, height: 1007, backgroundColor: imagePlaceholder }}
        src={image}
      />
      <img
        // you can also use require
        src={require("./assets/Macaca_nigra_self-portrait_large.jpg?placeholder&size=original&format=base64&esModule=false")}
      />
    </div>
  );
}

export default App;

// examples/vue/src/App.vue
<template>
  <div>
    <img
      style="width: 728px; height: 1007px"
      :style="{
        backgroundColor: require('@/assets/Macaca_nigra_self-portrait_large.jpg?placeholder'),
      }"
      src="@/assets/Macaca_nigra_self-portrait_large.jpg"
    />
    <img
      :src="
        require('@/assets/Macaca_nigra_self-portrait_large.jpg?placeholder&size=original&format=base64&esModule=false')
      "
    />
  </div>
</template>
